# Generated by Django 5.1.4 on 2025-01-13 16:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("marketplace", "0002_cart_cartitem"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cartitem",
            name="user",
        ),
        migrations.AddField(
            model_name="cartitem",
            name="cart",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="marketplace.cart",
            ),
            preserve_default=False,
        ),
    ]
